#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Lexical-Alias
version:      0.04
version_from: Alias.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_03
